default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('DATABASE_HOST') %>
  username: <%= ENV.fetch('DATABASE_USERNAME') %>
  password:
  pool: 5

development:
  <<: *default
  database: <%= "#{ENV.fetch('APP_NAME')}_development" %>

test:
  <<: *default
  database: <%= "#{ENV.fetch('APP_NAME')}_test" %>

staging:
  <<: *default
  database: <%= "#{ENV.fetch('APP_NAME')}_staging" %>

production:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>
