default: &default
  adapter: mysql2
  encoding: utf8
  charset: utf8
  collation: utf8_general_ci
  pool: 5
  timeout: 5000
  username: <%= ENV.fetch('DATABASE_USERNAME') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') %>
  host: <%= ENV.fetch('DATABASE_HOST') %>

development:
  <<: *default
  database: <%= "#{ENV.fetch('APP_NAME')}_development" %>

test:
  <<: *default
  database: <%= "#{ENV.fetch('APP_NAME')}_test" %>

production:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>