version: '2'
services:
  db:
    image: postgres
  redis:
    image: redis
  app:
    build: .
    env_file: .env
  web:
    extends:
      service: app
    command: sh -c 'rm tmp/pids/* || true && bundle exec rails s -p 3000 -b 0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    links:
      - db
      - redis
    tty: true
    stdin_open: true
  job:
    extends:
      service: app
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/myapp
    links:
      - db
      - redis